name: Trigger auto deployment for task-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/task-backend-AutoDeployTrigger-15f2244e-873a-41ff-9548-928de29f816f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TASKBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TASKBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TASKBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.TASKBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TASKBACKEND_REGISTRY_PASSWORD }}
          containerAppName: task-backend
          resourceGroup: primetrade
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


